// Map of canonical article titles (and common variants) → { category, slug }
const wikiLinkMap: Record<string, { category: string; slug: string }> = {
  // === CONCEPTS ===
  'Climate Finance': { category: 'concepts', slug: 'climate-finance' },
  'Green Finance': { category: 'concepts', slug: 'climate-finance' },
  'Physical Risks': { category: 'concepts', slug: 'physical-risks' },
  'Physical Risk': { category: 'concepts', slug: 'physical-risks' },
  'Transition Risks': { category: 'concepts', slug: 'transition-risks' },
  'Transition Risk': { category: 'concepts', slug: 'transition-risks' },
  'Stranded Assets': { category: 'concepts', slug: 'stranded-assets' },
  'Net Zero vs Carbon Neutral': { category: 'concepts', slug: 'net-zero-vs-carbon-neutral' },
  'Net Zero vs. Carbon Neutral': { category: 'concepts', slug: 'net-zero-vs-carbon-neutral' },
  'Net Zero': { category: 'concepts', slug: 'net-zero-vs-carbon-neutral' },
  'Carbon Neutral': { category: 'concepts', slug: 'net-zero-vs-carbon-neutral' },
  'net zero': { category: 'concepts', slug: 'net-zero-vs-carbon-neutral' },
  'Greenwashing': { category: 'concepts', slug: 'greenwashing' },
  'greenwashing': { category: 'concepts', slug: 'greenwashing' },
  'Greenwashing Typology': { category: 'concepts', slug: 'greenwashing-typology' },
  'Just Transition': { category: 'concepts', slug: 'just-transition' },
  'Adaptation vs Mitigation': { category: 'concepts', slug: 'adaptation-vs-mitigation' },
  'Adaptation vs. Mitigation': { category: 'concepts', slug: 'adaptation-vs-mitigation' },
  'Adaptation': { category: 'concepts', slug: 'adaptation-vs-mitigation' },
  'Mitigation': { category: 'concepts', slug: 'adaptation-vs-mitigation' },
  'GHG Scopes': { category: 'concepts', slug: 'ghg-scopes' },
  'Scope 1': { category: 'concepts', slug: 'ghg-scopes' },
  'Scope 2': { category: 'concepts', slug: 'ghg-scopes' },
  'Scope 3': { category: 'concepts', slug: 'ghg-scopes' },
  'Climate Litigation': { category: 'concepts', slug: 'climate-litigation' },
  'climate litigation': { category: 'concepts', slug: 'climate-litigation' },
  'The 1.5°C Threshold': { category: 'concepts', slug: 'the-1.5c-threshold' },
  '1.5°C': { category: 'concepts', slug: 'the-1.5c-threshold' },
  '1.5 degrees': { category: 'concepts', slug: 'the-1.5c-threshold' },

  // === INSTRUMENTS ===
  'Green Bonds': { category: 'instruments', slug: 'green-bonds' },
  'green bonds': { category: 'instruments', slug: 'green-bonds' },
  'Green Bond': { category: 'instruments', slug: 'green-bonds' },
  'Sustainability-Linked Bonds': { category: 'instruments', slug: 'sustainability-linked-bonds' },
  'SLBs': { category: 'instruments', slug: 'sustainability-linked-bonds' },
  'SLB': { category: 'instruments', slug: 'sustainability-linked-bonds' },
  'Sustainability-Linked Bond': { category: 'instruments', slug: 'sustainability-linked-bonds' },
  'Transition Bonds': { category: 'instruments', slug: 'transition-bonds' },
  'Transition Bond': { category: 'instruments', slug: 'transition-bonds' },
  'Carbon Offsets': { category: 'instruments', slug: 'carbon-offsets' },
  'carbon offsets': { category: 'instruments', slug: 'carbon-offsets' },
  'Carbon Credits': { category: 'instruments', slug: 'carbon-offsets' },
  'Cap-and-Trade': { category: 'instruments', slug: 'cap-and-trade' },
  'Cap and Trade': { category: 'instruments', slug: 'cap-and-trade' },
  'The Greenium': { category: 'instruments', slug: 'the-greenium' },
  'Greenium': { category: 'instruments', slug: 'the-greenium' },

  // === ACTORS ===
  'IPCC': { category: 'actors', slug: 'ipcc' },
  'Intergovernmental Panel on Climate Change': { category: 'actors', slug: 'ipcc' },
  'UNFCCC and COP': { category: 'actors', slug: 'unfccc-and-cop' },
  'UNFCCC': { category: 'actors', slug: 'unfccc-and-cop' },
  'COP': { category: 'actors', slug: 'unfccc-and-cop' },
  'Mark Carney and the Tragedy of the Horizon': { category: 'actors', slug: 'mark-carney' },
  'Mark Carney': { category: 'actors', slug: 'mark-carney' },
  'Tragedy of the Horizon': { category: 'actors', slug: 'mark-carney' },
  'CDP': { category: 'actors', slug: 'cdp' },
  'Climate Action 100+': { category: 'actors', slug: 'climate-action-100-plus' },
  'Climate Action 100': { category: 'actors', slug: 'climate-action-100-plus' },
  'CA100+': { category: 'actors', slug: 'climate-action-100-plus' },
  'GFANZ': { category: 'actors', slug: 'gfanz' },
  'Glasgow Financial Alliance for Net Zero': { category: 'actors', slug: 'gfanz' },
  'Science Based Targets Initiative': { category: 'actors', slug: 'science-based-targets-initiative' },
  'SBTi': { category: 'actors', slug: 'science-based-targets-initiative' },
  'Science Based Targets': { category: 'actors', slug: 'science-based-targets-initiative' },
  'Transition Pathway Initiative': { category: 'actors', slug: 'transition-pathway-initiative' },
  'TPI': { category: 'actors', slug: 'transition-pathway-initiative' },
  'Development Finance Institutions': { category: 'actors', slug: 'development-finance-institutions' },
  'DFIs': { category: 'actors', slug: 'development-finance-institutions' },
  'MDBs': { category: 'actors', slug: 'development-finance-institutions' },
  'World Bank': { category: 'actors', slug: 'development-finance-institutions' },

  // === FRAMEWORKS ===
  'Paris Agreement': { category: 'frameworks', slug: 'paris-agreement' },
  'Paris deal': { category: 'frameworks', slug: 'paris-agreement' },
  'TCFD': { category: 'frameworks', slug: 'tcfd' },
  'Task Force on Climate-related Financial Disclosures': { category: 'frameworks', slug: 'tcfd' },
  'IFRS S1 and S2': { category: 'frameworks', slug: 'ifrs-s1-s2' },
  'IFRS S1': { category: 'frameworks', slug: 'ifrs-s1-s2' },
  'IFRS S2': { category: 'frameworks', slug: 'ifrs-s1-s2' },
  'ISSB': { category: 'frameworks', slug: 'ifrs-s1-s2' },
  'ISSB standards': { category: 'frameworks', slug: 'ifrs-s1-s2' },
  'EU Taxonomy': { category: 'frameworks', slug: 'eu-taxonomy' },
  'EU taxonomy': { category: 'frameworks', slug: 'eu-taxonomy' },
  'CSRD': { category: 'frameworks', slug: 'csrd' },
  'Corporate Sustainability Reporting Directive': { category: 'frameworks', slug: 'csrd' },
  'SFDR': { category: 'frameworks', slug: 'sfdr' },
  'GHG Protocol': { category: 'frameworks', slug: 'ghg-protocol' },
  'Greenhouse Gas Protocol': { category: 'frameworks', slug: 'ghg-protocol' },
  'EU Green Deal': { category: 'frameworks', slug: 'eu-green-deal' },
  'European Green Deal': { category: 'frameworks', slug: 'eu-green-deal' },
  'Inflation Reduction Act': { category: 'frameworks', slug: 'inflation-reduction-act' },
  'IRA': { category: 'frameworks', slug: 'inflation-reduction-act' },
  'Green Bond Principles': { category: 'frameworks', slug: 'green-bond-principles' },
  'GBP': { category: 'frameworks', slug: 'green-bond-principles' },
  'ICMA Green Bond Principles': { category: 'frameworks', slug: 'green-bond-principles' },
  'Kyoto Protocol': { category: 'frameworks', slug: 'kyoto-protocol' },
  'Montreal Protocol': { category: 'frameworks', slug: 'montreal-protocol' },
  'Article 6': { category: 'frameworks', slug: 'article-6' },

  // === CASE STUDIES ===
  'Volkswagen Dieselgate': { category: 'case-studies', slug: 'volkswagen-dieselgate' },
  'VW Dieselgate': { category: 'case-studies', slug: 'volkswagen-dieselgate' },
  'Dieselgate': { category: 'case-studies', slug: 'volkswagen-dieselgate' },
  'HSBC Greenwashing': { category: 'case-studies', slug: 'hsbc-greenwashing' },
  'HSBC': { category: 'case-studies', slug: 'hsbc-greenwashing' },
  'DWS SEC Fine': { category: 'case-studies', slug: 'dws-sec-fine' },
  'DWS': { category: 'case-studies', slug: 'dws-sec-fine' },
  'PG&E Bankruptcy': { category: 'case-studies', slug: 'pge-bankruptcy' },
  'PG&E': { category: 'case-studies', slug: 'pge-bankruptcy' },
  'ENEL SLB': { category: 'case-studies', slug: 'enel-slb' },
  "ENEL's SLB": { category: 'case-studies', slug: 'enel-slb' },
  'Enel SLB': { category: 'case-studies', slug: 'enel-slb' },
  'Seychelles Blue Bond': { category: 'case-studies', slug: 'seychelles-blue-bond' },
  'Marfrig Transition Bond': { category: 'case-studies', slug: 'marfrig-transition-bond' },
  'Marfrig': { category: 'case-studies', slug: 'marfrig-transition-bond' },
  'Lombard Odier': { category: 'case-studies', slug: 'lombard-odier-ice-cubes' },
  'Lombard Odier Ice Cubes': { category: 'case-studies', slug: 'lombard-odier-ice-cubes' },
};

export function resolveWikilink(text: string): string | null {
  const entry = wikiLinkMap[text];
  if (!entry) return null;
  return `/${entry.category}/${entry.slug}/`;
}

export { wikiLinkMap };
